"""init"""

revision = '86b9c9dfbea1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_snippets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('feature', sa.String(length=255), nullable=True),
    sa.Column('feature_norm', sa.String(length=255), nullable=True),
    sa.Column('style_tag', sa.String(length=255), nullable=True),
    sa.Column('user_utterance', sa.Text(), nullable=True),
    sa.Column('response_case_raw', sa.String(length=255), nullable=True),
    sa.Column('response_case_norm', sa.String(length=255), nullable=True),
    sa.Column('response_case_tags', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('target_term', sa.String(length=255), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('must_use', sa.Boolean(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=64), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_ingestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('STYLE_GUIDE', 'APPROVED_STRING', 'GLOSSARY', 'CONTEXT', name='rag_source_type'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('embedding_vector_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_guide_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('feature_norm', sa.String(length=255), nullable=True),
    sa.Column('style_tag', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('DESIGNER', 'WRITER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('guardrail_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'FEATURE', 'REQUEST', name='guardrail_scope'), nullable=False),
    sa.Column('rule_type', sa.Enum('FORBIDDEN_TERM', 'REPLACE', 'LENGTH', 'STYLE', name='guardrail_rule_type'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('context_description', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=255), nullable=True),
    sa.Column('style_preferences', sa.Text(), nullable=True),
    sa.Column('constraints_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFTING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='request_status'), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_writer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_writer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='approval_decision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('llm_run_id', sa.String(length=255), nullable=True),
    sa.Column('generation_method', sa.Enum('AI', 'MANUAL', name='draft_generation_method'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.Enum('CSV', 'DOCX', 'NOTION', name='export_format'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='export_status'), nullable=False),
    sa.Column('result_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('version_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('draft_version_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='comment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['draft_version_id'], ['draft_versions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('draft_versions')
    op.drop_table('export_jobs')
    op.drop_table('drafts')
    op.drop_table('approvals')
    op.drop_table('requests')
    op.drop_table('guardrail_rules')
    op.drop_table('users')
    op.drop_table('style_guide_entries')
    op.drop_table('rag_ingestions')
    op.drop_table('glossary_entries')
    op.drop_table('context_snippets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
